# -*- coding: utf-8 -*-
f=open("c:/projetos/novoprojeto/site.html","w",encoding="utf-8")
f.write("<!DOCTYPE html><html lang=pt><head><meta charset=UTF-8><meta name=viewport content='width=device-width,initial-scale=1.0'><title>Central Mini Mateuzinho</title><style>")
f.write("*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a1a;color:#fff;font-family:sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh}.hidden{display:none!important}")
f.write(".card{background:#1a1a3e;border-radius:20px;padding:30px;text-align:center;max-width:420px;border:1px solid rgba(255,107,157,.3)}")
f.write("h1{font-size:1.8em;background:linear-gradient(45deg,#ff6b9d,#c44dff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin:10px 0}")
f.write(".btn{display:block;width:100%;padding:14px;margin:8px 0;border-radius:15px;border:none;cursor:pointer;font-size:1em;color:#fff;text-align:left}")
f.write(".pink{background:rgba(255,107,157,.2);border:2px solid #ff6b9d}.pink:hover{background:rgba(255,107,157,.4)}")
f.write(".purple{background:rgba(196,77,255,.2);border:2px solid #c44dff}.purple:hover{background:rgba(196,77,255,.4)}")
f.write(".green{background:#25d366;font-weight:bold;text-align:center;animation:glow 2s infinite}@keyframes glow{0%,100%{box-shadow:0 0 10px rgba(37,211,102,.3)}50%{box-shadow:0 0 25px rgba(37,211,102,.6)}}")
f.write(".chat{position:fixed;top:0;left:0;width:100%;height:100%;background:#0a0a1a;display:flex;flex-direction:column}")
f.write(".msgs{flex:1;overflow-y:auto;padding:15px;display:flex;flex-direction:column;gap:8px}")
f.write(".msg{max-width:80%;padding:10px 14px;border-radius:16px;font-size:.85em;line-height:1.4}")
f.write(".bot{background:#1a1a3e;align-self:flex-start;border-left:3px solid #c44dff}")
f.write(".user{background:linear-gradient(135deg,#ff6b9d,#c44dff);align-self:flex-end}")
f.write(".row{display:flex;gap:8px;padding:10px;background:#111133}")
f.write(".row input{flex:1;padding:10px;border-radius:20px;border:1px solid rgba(196,77,255,.3);background:#0d0d25;color:#fff;outline:none;font-size:.9em}")
f.write(".row button{background:linear-gradient(45deg,#ff6b9d,#c44dff);border:none;color:#fff;width:36px;height:36px;border-radius:50%;cursor:pointer;font-size:1em}")
f.write(".modal{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.85);z-index:200;display:flex;align-items:center;justify-content:center;padding:20px}")
f.write(".mcard{background:#111133;border-radius:20px;padding:25px;text-align:center;max-width:420px;width:100%;border:2px solid #25d366;max-height:90vh;overflow-y:auto}")
f.write(".svc{display:block;width:100%;background:#25d366;color:#fff;border:none;padding:10px;border-radius:12px;cursor:pointer;margin:4px 0;font-size:.9em}.svc:hover{background:#128c7e}")
f.write("</style></head><body>")
# Portal
f.write('<div id="portal"><div class="card">')
f.write('<div style="font-size:50px">'+chr(0x1F3E2)+'</div>')
f.write('<h1>Bem-vindo a Central de Ajuda<br>Mini Mateuzinho</h1>')
f.write('<p style="color:#aaa;margin:15px 0">Selecione seu perfil:</p>')
f.write('<button class="btn pink" onclick="entrar(1)"><span style="font-size:1.5em">'+chr(0x1F338)+'</span> Voce e <b>mei mei</b>?<br><small>Clique aqui</small></button>')
f.write('<button class="btn purple" onclick="entrar(2)"><span style="font-size:1.5em">'+chr(0x2728)+'</span> Voce e <b>kael</b>?<br><small>Clique aqui</small></button>')
f.write('<button style="background:transparent;border:none;color:#222;font-size:10px;margin-top:15px;cursor:default" onclick="admin()">'+chr(0x1F49C)+'</button>')
f.write('</div></div>')
# Chat screen
f.write('<div class="chat hidden" id="chat">')
f.write('<div style="padding:10px 15px;background:#111133;display:flex;justify-content:space-between;font-size:.85em"><span id="tit">'+chr(0x1F4AC)+' Central</span><span style="color:#2ecc71">'+chr(0x25CF)+' Online</span></div>')
f.write('<div class="msgs" id="msgs"></div>')
f.write('<div style="padding:5px 15px;color:#888;font-size:.75em" class="hidden" id="dig">Digitando...</div>')
f.write('<div class="row"><input id="inp" placeholder="Digite sua mensagem..." onkeypress="if(event.key===\'Enter\')env()"><button onclick="env()">'+chr(0x27A4)+'</button></div>')
f.write('<button class="btn green" onclick="humano()">'+chr(0x1F4DE)+' Falar com Mini Mateuzinho humano</button>')
f.write('<button class="btn" style="background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.3);color:#f66;margin-top:4px" onclick="voltar()">'+chr(0x1F6AA)+' Sair</button>')
f.write('</div>')
# Human modal
f.write('<div class="modal hidden" id="modH"><div class="mcard">')
f.write('<div style="font-size:40px">'+chr(0x1F916)+chr(0x27A1)+chr(0x1F49C)+'</div>')
f.write('<h2 style="color:#25d366;margin:8px 0">Conectando ao Mini Mateuzinho...</h2>')
f.write('<p id="msgH" style="color:#aaa;font-size:.85em;margin:8px 0"></p><div id="svcArea" style="margin:8px 0"></div>')
f.write('<div class="msgs" id="msgsH" style="max-height:150px;overflow-y:auto;margin:8px 0;text-align:left"></div>')
f.write('<div class="row"><input id="inpH" placeholder="Digite..." onkeypress="if(event.key===\'Enter\')envH()"><button onclick="envH()">'+chr(0x27A4)+'</button></div>')
f.write('<button class="btn" style="background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.4);color:#f66;margin-top:8px" onclick="document.getElementById(\'modH\').classList.add(\'hidden\')">Voltar ao bot</button>')
f.write('</div></div>')
# Admin modal
f.write('<div class="modal hidden" id="modA"><div class="mcard" style="border-color:#ff6b9d">')
f.write('<div style="font-size:35px">'+chr(0x1F49C)+'</div><h2 style="color:#ff6b9d;margin:8px 0">Painel do Mateuzinho</h2>')
f.write('<p style="color:#aaa;font-size:.75em">Cliente: <b id="cliA">---</b></p>')
f.write('<div class="msgs" id="msgsA" style="max-height:200px;overflow-y:auto;margin:8px 0;text-align:left;background:#0d0d25;border-radius:10px;padding:10px"></div>')
f.write('<div class="row"><input id="inpA" placeholder="Responder..." onkeypress="if(event.key===\'Enter\')envA()"><button onclick="envA()">'+chr(0x27A4)+'</button></div>')
f.write('<button class="btn" style="background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.4);color:#f66;margin-top:8px" onclick="document.getElementById(\'modA\').classList.add(\'hidden\')">Fechar</button>')
# JavaScript
f.write('<script>')
f.write('let cli="",ch=[];')
f.write('function entrar(c){cli=c==1?"sasa":"kael";document.getElementById("portal").classList.add("hidden");document.getElementById("chat").classList.remove("hidden");document.getElementById("tit").textContent="💬 Central - "+cli;document.getElementById("msgs").innerHTML="";dg(1);setTimeout(()=>{dg(0);if(c==1){addB("Oii mei mei! 💖 Bem-vinda a Central Mini Mateuzinho!");setTimeout(()=>addB("Sou o Mini Mateuzinho! Pode falar comigo ou clicar no botao verde!"),700)}else{addB("Oii kael! ✨ Sou o <b>robo</b> do Mini Mateuzinho");setTimeout(()=>addB("💡 Quer falar com o Mini de verdade? Clica no botao verde 📞!"),900)}},1200)}')
f.write('function voltar(){document.getElementById("chat").classList.add("hidden");document.getElementById("portal").classList.remove("hidden");document.getElementById("msgs").innerHTML=""}')
f.write('function addB(m){const d=document.createElement("div");d.className="msg bot";d.innerHTML=m;const e=document.getElementById("msgs");e.appendChild(d);e.scrollTop=e.scrollHeight}')
f.write('function addU(m){const d=document.createElement("div");d.className="msg user";d.textContent=m;const e=document.getElementById("msgs");e.appendChild(d);e.scrollTop=e.scrollHeight}')
f.write('function dg(s){document.getElementById("dig").classList.toggle("hidden",!s)}')
f.write('function env(){const i=document.getElementById("inp");const m=i.value.trim();if(!m)return;addU(m);i.value="";dg(1);setTimeout(()=>{dg(0);addB(responder(m))},800+Math.random()*1000)}')
f.write('function responder(m){const t=m.toLowerCase();const ik=cli==="kael";if(t.includes("oi")||t.includes("ola"))return ik?"Oii! Sou robo 🤖 Quer o Mini real? 📞":"Oii mei mei! 💖";if(t.includes("amor")||t.includes("amo"))return ik?"O Mini real vai amar! Fala com ele 📞":"Te amo demais! 💖";if(t.includes("jogar")||t.includes("jogo"))return "Temos joguinhos! Mas por enquanto so o chat 😊";return ik?"Sou robo! Chama o Mini real no botao verde 📞":"Pode falar o que quiser! 💜"}')
f.write('function salvar(){localStorage.setItem("ch_"+cli,JSON.stringify(ch))}')
f.write('function carregar(){const d=localStorage.getItem("ch_"+cli);if(d)ch=JSON.parse(d);else ch=[]}')
f.write('function addMH(de,msg){ch.push({de,msg,h:new Date().toLocaleTimeString()});salvar();rH();rA()}')
f.write('function rH(){const e=document.getElementById("msgsH");if(!e)return;e.innerHTML=ch.map(m=>"<div class=msg "+(m.de==="cliente"?"user":"bot")+" style=font-size:.72em><b>"+(m.de==="cliente"?"Voce":"Mateuzinho")+":</b> "+m.msg+"<br><small>"+m.h+"</small></div>").join("");e.scrollTop=e.scrollHeight}')
f.write('function rA(){const e=document.getElementById("msgsA");if(!e)return;e.innerHTML=ch.map(m=>"<div class=msg "+(m.de==="cliente"?"user":"bot")+" style=font-size:.72em><b>"+(m.de==="cliente"?"Cliente":"Voce")+":</b> "+m.msg+"<br><small>"+m.h+"</small></div>").join("");e.scrollTop=e.scrollHeight}')
s='<b>Boa tarde! Me chamo Mini Mateuzinho das empresas Mini Mateuzinho, tuturututu! [music]</b><br>Como podemos ajudar?'
s+='<button class=svc onclick=pedir("Tiracao de caucinha")>[shoes] Tiracao de caucinha</button>'
s+='<button class=svc onclick=pedir("Beijinho na boca")>[kiss] Beijinho na boca</button>'
s+='<button class=svc onclick=pedir("Fuki fuki")>[wind] Fuki fuki</button>'
s+='<button class=svc onclick=pedir("Copo de agua")>[drop] Copo de agua</button>'
f.write("function humano(){document.getElementById('modH').classList.remove('hidden');document.getElementById('msgH').innerHTML='"+s+"';document.getElementById('svcArea').innerHTML='"+s.split('<br>')[1]+"';carregar();rH();document.getElementById('inpH').value=''}")
f.write('function pedir(s){document.getElementById("inpH").value=s;envH()}')
f.write('function envH(){const i=document.getElementById("inpH");const m=i.value.trim();if(!m)return;addMH("cliente",m);i.value=""}')
f.write('function admin(){document.getElementById("modA").classList.remove("hidden");document.getElementById("cliA").textContent=cli||"---";carregar();rA();setInterval(()=>{carregar();rA()},2000)}')
f.write('function envA(){const i=document.getElementById("inpA");const m=i.value.trim();if(!m)return;addMH("mateuzinho",m);i.value=""}')
f.write('function limpar(){ch=[];salvar();rH();rA()}')
f.write('</script></body></html>')
f.close()
print("SITE GERADO COM SUCESSO! Arquivo: site.html")

f.write('<button class="btn" style="background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.4);color:#f66;margin-top:4px" onclick="limpar()">'+chr(0x1F5D1)+' Limpar conversa</button>')
f.write('</div></div>')
print("HTML OK")

print("CSS OK")
