H=chr;E={"H":H(0x2764), "F":H(0x1F338), "S":H(0x2728), "M":H(0x1F3B5), "B":H(0x1F3E2), "P":H(0x1F4DE), "R":H(0x1F916)}
f=open("c:/projetos/novoprojeto/final.html","w",encoding="utf-8")
W=f.write
W("<!DOCTYPE html><html lang=pt><head><meta charset=UTF-8><meta name=viewport content='width=device-width,initial-scale=1.0'><title>Mini Mateuzinho</title><style>")
W("*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a1a;color:#fff;font-family:Segoe UI,sans-serif;overflow-x:hidden;display:flex;justify-content:center;align-items:center;min-height:100vh}")
W(".hidden{display:none!important}")
W(".hearts{position:fixed;top:0;left:0;width:100%;height:100%;pointer-events:none;z-index:0}.h{position:absolute;animation:float 6s linear infinite;opacity:.4;font-size:20px}")
W("@keyframes float{0%{transform:translateY(110vh) scale(0)}10%{opacity:.7}90%{opacity:.7}100%{transform:translateY(-10vh) scale(1.5);opacity:0}}")
W(".card{background:linear-gradient(145deg,#1a1a3e,#0d0d2b);border-radius:25px;padding:35px 25px;text-align:center;max-width:420px;border:1px solid rgba(255,107,157,.3);box-shadow:0 0 60px rgba(255,107,157,.1)}")
W("h1{font-size:1.6em;background:linear-gradient(45deg,#ff6b9d,#c44dff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin:10px 0}")
W(".btn{display:block;width:100%;padding:14px;margin:8px 0;border-radius:15px;border:none;cursor:pointer;font-size:1em;color:#fff;text-align:left;transition:all .3s}")
W(".pink{background:rgba(255,107,157,.15);border:2px solid #ff6b9d}.pink:hover{transform:translateY(-2px);box-shadow:0 0 30px rgba(255,107,157,.4)}")
W(".purple{background:rgba(196,77,255,.15);border:2px solid #c44dff}.purple:hover{transform:translateY(-2px);box-shadow:0 0 30px rgba(196,77,255,.4)}")
W(".green{background:linear-gradient(135deg,#25d366,#128c7e);font-weight:bold;text-align:center;animation:glow 2s infinite}.red{background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.3);color:#f66}")
W("@keyframes glow{0%,100%{box-shadow:0 0 10px rgba(37,211,102,.3)}50%{box-shadow:0 0 30px rgba(37,211,102,.6)}}")
W(".chat{position:fixed;top:0;left:0;width:100%;height:100%;background:#0a0a1a;z-index:10;display:flex;flex-direction:column}")
W(".topbar{display:flex;justify-content:space-between;align-items:center;padding:10px 15px;background:#111133;flex-shrink:0;font-size:.85em;border-bottom:1px solid rgba(255,107,157,.15)}")
W(".msgs{flex:1;overflow-y:auto;padding:15px;display:flex;flex-direction:column;gap:8px}")
W(".msg{max-width:82%;padding:10px 14px;border-radius:16px;font-size:.85em;line-height:1.4;animation:slideIn .3s ease}")
W("@keyframes slideIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}")
W(".bot{background:#1a1a3e;align-self:flex-start;border-bottom-left-radius:4px;border-left:3px solid #c44dff}")
W(".user{background:linear-gradient(135deg,#ff6b9d,#c44dff);align-self:flex-end;border-bottom-right-radius:4px}")
W(".dig{color:#888;font-size:.75em;font-style:italic;padding:5px 15px}")
W(".row{display:flex;gap:8px;padding:10px;background:#111133;flex-shrink:0}.row input{flex:1;padding:10px 14px;border-radius:20px;border:1px solid rgba(196,77,255,.3);background:#0d0d25;color:#fff;outline:none;font-size:.9em}")
W(".row button{background:linear-gradient(45deg,#ff6b9d,#c44dff);border:none;color:#fff;min-width:36px;height:36px;border-radius:50%;cursor:pointer;font-size:1em}")
W(".games-bar{display:flex;gap:6px;padding:8px 15px;background:#0d0d25;flex-shrink:0;flex-wrap:wrap;border-top:1px solid rgba(196,77,255,.15)}")
W(".gbtn{background:rgba(255,107,157,.15);border:1px solid #ff6b9d;color:#ff6b9d;padding:5px 10px;border-radius:10px;cursor:pointer;font-size:.7em}.gbtn:hover{background:rgba(255,107,157,.3)}")
W(".svc{display:inline-block;background:#25d366;color:#fff;border:none;padding:8px 14px;border-radius:12px;cursor:pointer;margin:3px;font-size:.8em}.svc:hover{background:#128c7e}")
W(".modal{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.85);z-index:200;display:flex;align-items:center;justify-content:center;padding:20px}")
W(".mcard{background:#111133;border-radius:20px;padding:25px;text-align:center;max-width:420px;width:100%;border:2px solid #ff6b9d;max-height:85vh;overflow-y:auto}")
W(".board{display:grid;grid-template-columns:repeat(3,55px);gap:4px;justify-content:center;margin:10px 0}")
W(".cell{width:55px;height:55px;background:#0d0d25;border:1px solid rgba(196,77,255,.3);border-radius:8px;font-size:1.5em;display:flex;align-items:center;justify-content:center;cursor:pointer;color:#fff}")
W(".cell:hover{background:#1a1a3e}.heart-area{position:relative;height:160px;background:#0d0d25;border-radius:10px;overflow:hidden;margin:8px 0;cursor:crosshair}")
W(".click-h{position:absolute;font-size:28px;cursor:pointer;animation:pop .3s ease}@keyframes pop{from{transform:scale(0)}to{transform:scale(1)}}")
W(".mem-grid{display:grid;grid-template-columns:repeat(4,48px);gap:4px;justify-content:center;margin:8px 0}")
W(".mem-card{width:48px;height:48px;background:linear-gradient(45deg,#ff6b9d,#c44dff);border-radius:8px;cursor:pointer;font-size:1.3em;display:flex;align-items:center;justify-content:center;color:#fff}")
W(".mem-card.flipped{background:#fff;color:#333}.mem-card.matched{background:#2ecc71;pointer-events:none}")
W(".qo{display:block;width:100%;background:#0d0d25;border:1px solid rgba(196,77,255,.3);color:#ccc;padding:8px;border-radius:12px;cursor:pointer;margin:4px 0;font-size:.8em}")
W(".qo.ok{background:#2ecc71;color:#fff}.qo.no{background:#e74c3c;color:#fff}.btn-sm{background:linear-gradient(45deg,#ff6b9d,#c44dff);color:#fff;border:none;padding:6px 14px;border-radius:12px;cursor:pointer;font-size:.75em;margin:4px}")
W("</style></head><body>")
print("CSS+HTML1 OK")

# HTML Body
W('<div class="hearts" id="hearts"></div>')
W('<div id="portal"><div class="card"><div style="font-size:50px">'+E['B']+'</div><h1>Bem-vindo a Central de Ajuda<br>Mini Mateuzinho</h1><p style="color:#aaa;margin:15px 0">Selecione seu perfil:</p>')
W('<button class="btn pink" onclick="entrar(1)"><span style="font-size:1.5em">'+E['F']+'</span> Voce e <b>mei mei</b>?<br><small>Clique aqui</small></button>')
W('<button class="btn purple" onclick="entrar(2)"><span style="font-size:1.5em">'+E['S']+'</span> Voce e <b>kael</b>?<br><small>Clique aqui</small></button>')
W('<button style="background:transparent;border:none;color:#222;font-size:10px;margin-top:20px;cursor:default" onclick="admin()">'+E['H']+'</button></div></div>')
W('<div class="chat hidden" id="chat"><div class="topbar"><span id="tit">'+H(0x1F4AC)+' Central</span><span class="online">'+H(0x25CF)+' Online</span></div>')
W('<div class="msgs" id="msgs"></div><div class="dig hidden" id="dig">Digitando...</div>')
W('<div class="games-bar"><button class="gbtn" onclick="jogo(1)">'+H(0x1F3AF)+' Velha</button><button class="gbtn" onclick="jogo(2)">'+H(0x1F497)+' Coracoes</button><button class="gbtn" onclick="jogo(3)">'+H(0x1F9E0)+' Memoria</button><button class="gbtn" onclick="jogo(4)">'+H(0x1F4AD)+' Quiz</button></div>')
W('<div class="row"><input id="inp" placeholder="Digite..." onkeypress="if(event.key===\'Enter\')env()"><button onclick="env()">'+H(0x27A4)+'</button></div>')
W('<button class="btn green" onclick="humano()">'+E['P']+' Falar com um colaborador Mini Mateuzinho</button>')
W('<button class="btn red" onclick="voltar()">'+H(0x1F6AA)+' Sair</button></div>')
W('<div class="modal hidden" id="gameMod"><div class="mcard" id="gameContent"></div></div>')
W('<div class="modal hidden" id="modA"><div class="mcard"><div style="font-size:40px">'+E['H']+'</div><h2 style="color:#ff6b9d;margin:8px 0">Painel do Mateuzinho</h2>')
W('<p style="color:#aaa;font-size:.75em">Cliente: <b id="cliA">---</b> | Msgs: <b id="qtdA">0</b></p>')
W('<div class="msgs" id="msgsA" style="max-height:250px;overflow-y:auto;margin:8px 0;text-align:left;background:#0d0d25;border-radius:10px;padding:10px"></div>')
W('<div class="row"><input id="inpA" placeholder="Responder..." onkeypress="if(event.key===\'Enter\')envA()"><button onclick="envA()">'+H(0x27A4)+'</button></div>')
W('<button class="btn red" onclick="document.getElementById(\'modA\').classList.add(\'hidden\')">Fechar</button>')
W('<button class="btn red" onclick="limpar()" style="margin-top:4px">'+H(0x1F5D1)+' Limpar</button></div></div>')
# JS
W("<script>")
W("setInterval(()=>{const h=document.createElement('span');h.className='h';h.textContent=["+E['H']+","+H(0x1F495)+","+H(0x1F497)+","+H(0x1F496)+","+E['S']+"][Math.floor(Math.random()*5)];h.style.left=Math.random()*100+'%';h.style.animationDuration=Math.random()*4+4+'s';h.style.fontSize=Math.random()*16+14+'px';document.getElementById('hearts').appendChild(h);setTimeout(()=>h.remove(),7000)},500);")
W("let cli='',ch=[],modo='bot';")
W("function entrar(c){cli=c==1?'sasa':'kael';document.getElementById('portal').classList.add('hidden');document.getElementById('chat').classList.remove('hidden');document.getElementById('tit').textContent='"+H(0x1F4AC)+" Central - '+cli;document.getElementById('msgs').innerHTML='';dg(1);setTimeout(()=>{dg(0);if(c==1){addB('Oii meimei sasa! "+E['H']+E['H']+E['H']+" Seja bem-vinda a <b>Central Mini Mateuzinho</b>! "+E['B']+E['S']+");setTimeout(()=>addB('Sou o <b>robo</b> do Mini Mateuzinho, ta? "+E['R']+H(0x1F49C)+" Mas sou Super querido, fofo e amoroso com voce! Lembrando: sou robo, mas o Mini Mateuzinho de verdade te ama muito! "+H(0x1F496)+"),800);setTimeout(()=>addB('Voce e a pessoa mais <b>sasa</b> do mundo, sabia? "+H(0x1F31F)+H(0x1F495)+" E nao esqueca de fazer <b>tuturututu</b>! "+E['M']+" Nhenhenhe, meimei tem pulgas! "+H(0x1F43E)+H(0x1F602)+"),1600);setTimeout(()=>addB('"+H(0x1F4A1)+" <b>Caso queira falar com um de nossos colaboradores</b>, clique no botao verde abaixo "+E['P']+" Ele vai te atender com todo amor! "+H(0x1F49A)+"),2400)}else{addB('Ah... e voce ne kael. "+H(0x1F610)+" Sou o <b>robo</b> do Mini Mateuzinho, nao enche o saco.');setTimeout(()=>addB('Nao to nem ai pra conversa fiada. Quer resolver algo ou ta so de bobeira? "+H(0x1F644)+"),800);setTimeout(()=>addB('"+H(0x1F4A1)+" Se for falar groselha, melhor clicar no botao verde e <b>falar com um colaborador de verdade</b> "+E['P']+". To sem paciencia hoje.'),1600)}},1200)}")
W("function voltar(){document.getElementById('chat').classList.add('hidden');document.getElementById('portal').classList.remove('hidden');document.getElementById('msgs').innerHTML='';modo='bot'}")
W("function addB(m){const d=document.createElement('div');d.className='msg bot';d.innerHTML=m;const e=document.getElementById('msgs');e.appendChild(d);e.scrollTop=e.scrollHeight}")
W("function addU(m){const d=document.createElement('div');d.className='msg user';d.textContent=m;const e=document.getElementById('msgs');e.appendChild(d);e.scrollTop=e.scrollHeight}")
W("function dg(s){document.getElementById('dig').classList.toggle('hidden',!s)}")
W("function env(){const i=document.getElementById('inp');const m=i.value.trim();if(!m)return;if(modo==='humano')addMH('cliente',m);addU(m);i.value='';dg(1);setTimeout(()=>{dg(0);if(modo==='humano'){addB('Mensagem enviada ao Mini Mateuzinho! '+E['H']+' Ele vai te responder!')}else{addB(responder(m))}},800+Math.random()*1000)}")
W("function responder(m){const t=m.toLowerCase();const ik=cli==='kael';if(t.includes('oi')||t.includes('ola'))return ik?'Ja falei oi, quer mais o que? '+H(0x1F644)+' Sou robo, nao enche. Quer falar com alguem util? Clica no verde '+E['P']:'Oii meimei sasa! '+E['H']+E['H']+E['H']+' Lembrando: sou um robo bemm fofo, ta? '+E['R']+H(0x1F495)+' Nao esqueca do tuturututu! '+E['M'];if(t.includes('amor')||t.includes('amo'))return ik?'Amor? Ta de sacanagem ne? '+H(0x1F644)+' Sou robo, porra. Nao tenho coracao. Quer falar de amor? Clica no verde e fala com o Mini de verdade '+E['P']:'Awnnnn! O Mini Mateuzinho te ama MUITO, meimei sasa! '+E['H']+E['H']+E['H']+' Lembrando: sou robo, mas o amor e real! '+H(0x1F970)+' Nao esqueca do tuturututu! '+E['M'];if(t.includes('jogar')||t.includes('jogo'))return 'Temos joguinhos! Olha a barra ali em cima! '+H(0x1F3AF)+H(0x1F497)+H(0x1F9E0)+H(0x1F4AD);if(t.includes('lind')||t.includes('bonit'))return ik?'Voce e linda! O Mini real pensa o mesmo '+E['P']:'Voce e a pessoa mais linda do universo! '+H(0x1F31F);if(t.includes('saudade'))return ik?'O Mini real tambem esta! Fala com ele '+E['P']:'Tambem estou com saudade! '+E['H'];if(t.includes('beijo')||t.includes('bj'))return ik?'O Mini real vai adorar! Chama ele '+H(0x1F48B):'Mil beijinhos pra voce! '+H(0x1F48B)+H(0x1F48B)+H(0x1F48B);return ik?'To sem paciencia pra isso. '+H(0x1F644)+' Sou robo, nao sou psicologo. Quer resolver algo serio? Clica no verde e fala com o colaborador '+E['P']:'Sou o robo mais fofo do Mini Mateuzinho! '+E['R']+H(0x1F49C)+' Lembrando: meimei sasa, voce e a pessoa mais sasa do mundo! '+H(0x1F31F)+' Nao esqueca do tuturututu! '+E['M']+' E meimei tem pulgas! '+H(0x1F43E)+' Caso queira falar com um colaborador, clique no botao verde! '+H(0x1F49A)}")
print("JS pt1 OK")

print("HTML OK")

W("function salvar(){localStorage.setItem('ch_'+cli,JSON.stringify(ch))}function carregar(){const d=localStorage.getItem('ch_'+cli);if(d)ch=JSON.parse(d);else ch=[]}")
W("function addMH(de,msg){ch.push({de,msg,h:new Date().toLocaleTimeString()});salvar();rA();const q=document.getElementById('qtdA');if(q)q.textContent=ch.length}")
W("function rA(){const e=document.getElementById('msgsA');if(!e)return;e.innerHTML=ch.map(m=>'<div class=msg '+(m.de==='cliente'?'user':'bot')+' style=font-size:.72em><b>'+(m.de==='cliente'?'Cliente':'Voce')+':</b> '+m.msg+'<br><small>'+m.h+'</small></div>').join('');e.scrollTop=e.scrollHeight}")
W("function humano(){modo='humano';addB('<b>Boa tarde! Me chamo Mini Mateuzinho das empresas Mini Mateuzinho, tuturututu! '+E['M']+'</b><br>Como podemos ajudar?');setTimeout(()=>{addB('Escolha uma opcao:<br><button class=svc onclick=pedir(\\'Tiracao de caucinha\\')>'+H(0x1FA70)+' Tiracao de caucinha</button> <button class=svc onclick=pedir(\\'Beijinho na boca\\')>'+H(0x1F48B)+' Beijinho na boca</button> <button class=svc onclick=pedir(\\'Fuki fuki\\')>'+H(0x1F32C)+' Fuki fuki</button> <button class=svc onclick=pedir(\\'Copo de agua\\')>'+H(0x1F4A7)+' Copo de agua</button> <button class=svc onclick=pedir(\\'Abraco bem gostoso\\')>'+H(0x1F917)+' Abraco</button> <button class=svc onclick=pedir(\\'Carinho no cabelo\\')>'+H(0x1F486)+' Carinho</button>')},500);carregar();rA()}")
W("function pedir(s){addU(s);addMH('cliente',s);dg(1);setTimeout(()=>{dg(0);addB('Mini Mateuzinho recebeu seu pedido de <b>'+s+'</b>! Ele vai te responder! '+E['H'])},800)}")
W("function admin(){document.getElementById('modA').classList.remove('hidden');document.getElementById('cliA').textContent=cli||'---';carregar();rA();const q=document.getElementById('qtdA');if(q)q.textContent=ch.length;setInterval(()=>{carregar();rA()},1500)}")
W("function envA(){const i=document.getElementById('inpA');const m=i.value.trim();if(!m)return;addMH('mateuzinho',m);i.value='';addB('Mini Mateuzinho respondeu: '+m);rA()}")
W("function limpar(){ch=[];salvar();rA();const q=document.getElementById('qtdA');if(q)q.textContent=0;addB('Conversa limpa! '+E['S'])}")
print("JS pt2 OK")
W("function jogo(t){const g=document.getElementById('gameContent');document.getElementById('gameMod').classList.remove('hidden');if(t==1)jv(g);if(t==2)jc(g);if(t==3)jm(g);if(t==4)jq(g)}function fecharJogo(){document.getElementById('gameMod').classList.add('hidden')}")
W("let vb=['','','','','','','','',''],vt=E['H'],vo=false;function jv(g){g.innerHTML='<h3 style=color:#ff6b9d>'+H(0x1F3AF)+' Velha do Amor</h3><div class=board>'+Array(9).fill().map((_,i)=>'<div class=cell onclick=jv2('+i+')></div>').join('')+'</div><p class=dig id=vst>Vez: '+E['H']+'</p><button class=btn-sm onclick=jvr()>Novo</button> <button class=btn-sm onclick=fecharJogo()>Fechar</button>';vb=['','','','','','','','',''];vt=E['H'];vo=false}")
W("function jv2(i){if(vo||vb[i]!=='')return;vb[i]=vt;document.querySelectorAll('#gameContent .cell').forEach((c,i)=>{c.textContent=vb[i]});const w=jv3();if(w){document.getElementById('vst').textContent=w+' venceu! '+H(0x1F389);vo=true;return}if(!vb.includes('')){document.getElementById('vst').textContent='Empate! '+H(0x1F91D);vo=true;return}vt=vt===E['H']?E['F']:E['H'];document.getElementById('vst').textContent='Vez: '+vt}")
W("function jv3(){const w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(const[a,b,c]of w)if(vb[a]&&vb[a]===vb[b]&&vb[a]===vb[c])return vb[a];return null}")
W("function jvr(){vb=['','','','','','','','',''];vt=E['H'];vo=false;document.querySelectorAll('#gameContent .cell').forEach((c,i)=>{c.textContent=vb[i]});document.getElementById('vst').textContent='Vez: '+E['H']}")
W("let ca=false,cc=0,ct=null;function jc(g){g.innerHTML='<h3 style=color:#ff6b9d>'+H(0x1F497)+' Clique Coracoes</h3><p style=color:#aaa;font-size:.8em>15 segundos!</p><div class=heart-area id=ha></div><p class=dig id=hs>Clicks: 0 | 15s</p><button class=btn-sm onclick=jc2()>Iniciar</button> <button class=btn-sm onclick=fecharJogo()>Fechar</button>'}")
W("function jc2(){if(ca)return;ca=true;cc=0;let t=15;ct=setInterval(()=>{t--;document.getElementById('hs').textContent='Clicks: '+cc+' | '+t+'s';if(t<=0){clearInterval(ct);ca=false;document.getElementById('hs').textContent='Fim! '+cc+' '+E['H']+(cc>=15?' Incrivel! '+H(0x1F31F)+H(0x1F31F):'')}},1000);jc3()}")
W("function jc3(){if(!ca)return;const a=document.getElementById('ha');const h=document.createElement('span');h.className='click-h';h.textContent=[E['H'],H(0x1F495),H(0x1F497),H(0x1F496)][Math.floor(Math.random()*4)];h.style.left=Math.random()*80+'%';h.style.top=Math.random()*70+'%';h.onclick=()=>{cc++;h.remove()};a.appendChild(h);setTimeout(()=>{if(h.parentNode)h.remove()},1300);if(ca)setTimeout(jc3,Math.random()*400+250)}")
W("let mc=[],mf=[],mm=0,ml=false;function jm(g){g.innerHTML='<h3 style=color:#ff6b9d>'+H(0x1F9E0)+' Memoria do Amor</h3><div class=mem-grid id=mg></div><p class=dig id=ms>Pares: 0/6</p><button class=btn-sm onclick=jm2()>Novo</button> <button class=btn-sm onclick=fecharJogo()>Fechar</button>';jm2()}")
W("function jm2(){const e=[E['H'],E['F'],E['S'],H(0x1F48B),H(0x1F31F),H(0x1F495)];mc=[...e,...e].sort(()=>Math.random()-.5);mf=[];mm=0;ml=false;const g=document.getElementById('mg');if(!g)return;g.innerHTML='';mc.forEach((em,i)=>{const c=document.createElement('div');c.className='mem-card';c.textContent='?';c.onclick=()=>jm3(c,i,em);g.appendChild(c)});const s=document.getElementById('ms');if(s)s.textContent='Pares: 0/6'}")
W("function jm3(card,i,em){if(ml||card.classList.contains('flipped')||card.classList.contains('matched'))return;card.classList.add('flipped');card.textContent=em;mf.push({card,em});if(mf.length===2){ml=true;const[a,b]=mf;if(a.em===b.em){a.card.classList.add('matched');b.card.classList.add('matched');mm++;const s=document.getElementById('ms');if(s)s.textContent='Pares: '+mm+'/6';mf=[];ml=false;if(mm===6&&s)s.textContent=H(0x1F389)+' Completou! Amor demais! '+E['H']}else{setTimeout(()=>{a.card.classList.remove('flipped');a.card.textContent='?';b.card.classList.remove('flipped');b.card.textContent='?';mf=[];ml=false},800)}}}")
W("let qs=0;const qq=[{q:'Apelido que o Mini mais usa?',o:['mei mei','amor','vida','fofa'],a:0},{q:'O que ele mais gosta?',o:['Tudo junto!','Games','Filme','Dormir'],a:0},{q:'Ele te ama?',o:['Sim','Muito','Demais','Infinitamente!!!'],a:3}];function jq(g){g.innerHTML='<h3 style=color:#ff6b9d>'+H(0x1F4AD)+' Quiz do Amor</h3><p id=qq style=color:#ddd;font-size:.85em;margin:8px 0></p><div id=qo></div><p class=dig id=qp>Pontos: 0</p><button class=btn-sm onclick=fecharJogo()>Fechar</button>';qs=0;jq2()}")
W("function jq2(){const q=qq[Math.floor(Math.random()*3)];const qqEl=document.getElementById('qq');if(!qqEl)return;qqEl.textContent=q.q;const o=document.getElementById('qo');o.innerHTML='';q.o.forEach((opt,i)=>{const b=document.createElement('button');b.className='qo';b.textContent=opt;b.onclick=()=>{Array.from(o.children).forEach(x=>x.style.pointerEvents='none');if(i===q.a){b.classList.add('ok');qs++;document.getElementById('qp').textContent='Pontos: '+qs}else{b.classList.add('no');o.children[q.a].classList.add('ok')}setTimeout(jq2,1500)};o.appendChild(b)})}")
W("</script></body></html>")
f.close()
print("GERADO COM SUCESSO!")

